# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kinetix.risk import counterparty_risk_pb2 as kinetix_dot_risk_dot_counterparty__risk__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kinetix/risk/counterparty_risk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CounterpartyRiskServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculatePFE = channel.unary_unary(
                '/kinetix.risk.CounterpartyRiskService/CalculatePFE',
                request_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFERequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFEResponse.FromString,
                _registered_method=True)
        self.CalculateCVA = channel.unary_unary(
                '/kinetix.risk.CounterpartyRiskService/CalculateCVA',
                request_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVARequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVAResponse.FromString,
                _registered_method=True)


class CounterpartyRiskServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def CalculatePFE(self, request, context):
        """Monte Carlo simulation of Potential Future Exposure for a netting set.
        This is compute-intensive; callers should cache results and use for batch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateCVA(self, request, context):
        """Credit Valuation Adjustment using discrete tenor approximation.
        On-demand capable; requires a pre-computed exposure profile from PFE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CounterpartyRiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculatePFE': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePFE,
                    request_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFERequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFEResponse.SerializeToString,
            ),
            'CalculateCVA': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateCVA,
                    request_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVARequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.CounterpartyRiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.CounterpartyRiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CounterpartyRiskService(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CalculatePFE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.CounterpartyRiskService/CalculatePFE',
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFERequest.SerializeToString,
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculatePFEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateCVA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.CounterpartyRiskService/CalculateCVA',
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVARequest.SerializeToString,
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateCVAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SaCcrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateSaCcr = channel.unary_unary(
                '/kinetix.risk.SaCcrService/CalculateSaCcr',
                request_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrRequest.SerializeToString,
                response_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrResponse.FromString,
                _registered_method=True)


class SaCcrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateSaCcr(self, request, context):
        """SA-CCR (BCBS 279) regulatory EAD calculation for a netting set.
        Deterministic, formulaic — NOT Monte Carlo simulation.
        Use for regulatory capital reporting; use CalculatePFE for internal limits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaCcrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateSaCcr': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSaCcr,
                    request_deserializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrRequest.FromString,
                    response_serializer=kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kinetix.risk.SaCcrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kinetix.risk.SaCcrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SaCcrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateSaCcr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kinetix.risk.SaCcrService/CalculateSaCcr',
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrRequest.SerializeToString,
            kinetix_dot_risk_dot_counterparty__risk__pb2.CalculateSaCcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
