ALTER TABLE valuation_jobs ADD COLUMN delta DOUBLE PRECISION;
ALTER TABLE valuation_jobs ADD COLUMN gamma DOUBLE PRECISION;
ALTER TABLE valuation_jobs ADD COLUMN vega DOUBLE PRECISION;
ALTER TABLE valuation_jobs ADD COLUMN theta DOUBLE PRECISION;
ALTER TABLE valuation_jobs ADD COLUMN rho DOUBLE PRECISION;
